apiVersion: v1
kind: Service
metadata:
  name: {{ template "enterprise-logs.fullname" . }}-gateway
  labels:
    {{- with .Values.gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.gateway.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ template "enterprise-logs.http-listen-port" . }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "enterprise-logs.selectorLabels" . | nindent 4 }}
