{{- if not .Values.useExternalLicense -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enterprise-logs.fullname" . }}-license
  labels:
    {{- include "enterprise-logs.labels" . | nindent 4 }}
data:
  license.jwt: {{ .Values.license.contents | b64enc }}
{{- end }}
