{{- if not .Values.license.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enterprise-logs.fullname" . }}
  labels:
    {{- include "enterprise-logs.labels" . | nindent 4 }}
data:
  license.jwt: {{ .Values.license.contents | b64enc }}
{{- end }}
