apiVersion: v1
kind: Service
metadata:
  name: {{ template "enterprise-logs.fullname" . }}-admin-api
  labels:
    {{- include "enterprise-logs.labels" . | nindent 4 }}
    {{- with .Values.adminApi.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.adminApi.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ template "enterprise-logs.http-listen-port" . }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ template "enterprise-logs.grpc-listen-port" . }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "enterprise-logs.selectorLabels" . | nindent 4 }}
